// Plinko math engine.
//
// Architecture (see also web/scripts/plinko-math.ts):
//
//   - Each row of pegs is an independent fair coin flip (50/50 left/right).
//   - With n rows there are n+1 buckets. Bucket k is hit when the ball makes
//     exactly k "right" choices, so P(k) = C(n,k) / 2^n.
//   - Negative EV is implemented via the multiplier table, NOT via biased
//     physics. Multipliers are scaled so that EV = targetRTP < 1.
//   - The renderer animates a guided ball along the bit-array path; the ball
//     is forced to land in the predetermined bucket so visuals always match
//     the payout. See PlinkoBoard.addBall.
//
// 10k Monte-Carlo EV by (rows, risk) is generated by `scripts/plinko-math.ts`
// and embedded as a comment block at the bottom of this file.

export const PLINKO_ROWS = [8, 12, 16] as const;
export type PlinkoRows = (typeof PLINKO_ROWS)[number];

export const MIN_BET_USDC = 0.1;
export const MIN_BET_UNITS = 100_000;
export const USDC_UNITS = 1_000_000;

export type RiskLevel = 'low' | 'medium' | 'high';
export const RISK_LEVELS: readonly RiskLevel[] = ['low', 'medium', 'high'] as const;

export const DEFAULT_RISK: RiskLevel = 'medium';
export const DEFAULT_TARGET_RTP = 0.70;

// Curve "spikiness" by risk: raw_mult[k] ∝ (P_center / P_k)^alpha. After
// uniform scaling to targetRTP, low alpha gives flat tables (low variance,
// modest jackpots), high alpha gives spiky tables (high variance, huge
// jackpots that are extremely rare). All risk modes share the same EV.
const ALPHA_BY_RISK: Record<RiskLevel, number> = {
  low: 0.35,
  medium: 0.55,
  high: 0.8,
};

export function isPlinkoRows(value: number): value is PlinkoRows {
  return value === 8 || value === 12 || value === 16;
}

export function isRiskLevel(value: unknown): value is RiskLevel {
  return value === 'low' || value === 'medium' || value === 'high';
}

export function unitsToUsdc(units: number | bigint): string {
  const n = typeof units === 'bigint' ? Number(units) : units;
  return (n / USDC_UNITS).toFixed(6);
}

export function parseUsdcToUnits(value: unknown): bigint | null {
  const raw = String(value ?? '').trim();
  if (!/^\d+(\.\d{1,6})?$/.test(raw)) return null;
  const [whole, fraction = ''] = raw.split('.');
  return BigInt(whole) * BigInt(USDC_UNITS) + BigInt(fraction.padEnd(6, '0'));
}

function binomCoeff(n: number, k: number): number {
  if (k < 0 || k > n) return 0;
  if (k === 0 || k === n) return 1;
  let r = 1;
  const iters = Math.min(k, n - k);
  for (let i = 0; i < iters; i++) {
    r = (r * (n - i)) / (i + 1);
  }
  return r;
}

/** P(slot k) under fair binomial draw: C(n,k)/2^n. Sums to 1. */
export function binomialProbabilities(rows: PlinkoRows): number[] {
  const probs: number[] = [];
  for (let k = 0; k <= rows; k++) {
    probs.push(binomCoeff(rows, k) / Math.pow(2, rows));
  }
  return probs;
}

/** Single-bucket binomial probability — kept as a named export for tests. */
export function binProbability(n: number, k: number): number {
  return binomCoeff(n, k) / Math.pow(2, n);
}

/**
 * Build a payout table such that EV = targetRTP under the binomial draw.
 *
 * Shape: raw_mult[k] = (P_center / P_k)^alpha. Center bucket (highest
 * probability) gets the smallest raw value (1.0); edges get the largest.
 * Then scale uniformly so sum(P_k * mult_k) = targetRTP.
 *
 * Symmetry: since P_k = P_{n-k}, raw_mult[k] = raw_mult[n-k]. We re-symmetrize
 * after computation to kill float-roundoff drift.
 */
export function generateMultipliers(
  rows: PlinkoRows,
  riskLevel: RiskLevel = DEFAULT_RISK,
  targetRTP: number = DEFAULT_TARGET_RTP,
): number[] {
  const probs = binomialProbabilities(rows);
  const center = Math.floor(rows / 2);
  const centerProb = probs[center];
  const alpha = ALPHA_BY_RISK[riskLevel];

  const raw = probs.map((p) => Math.pow(centerProb / p, alpha));

  for (let i = 0; i < center; i++) {
    const sym = (raw[i] + raw[rows - i]) / 2;
    raw[i] = sym;
    raw[rows - i] = sym;
  }

  const evRaw = raw.reduce((s, m, k) => s + probs[k] * m, 0);
  const scale = targetRTP / evRaw;
  return raw.map((m) => m * scale);
}

const _multCache = new Map<string, number[]>();

/** Memoized multiplier table for (rows, riskLevel). */
export function getMultipliers(
  rows: PlinkoRows,
  riskLevel: RiskLevel = DEFAULT_RISK,
): number[] {
  const key = `${rows}:${riskLevel}`;
  let m = _multCache.get(key);
  if (!m) {
    m = generateMultipliers(rows, riskLevel);
    _multCache.set(key, m);
  }
  return m;
}

/** Closed-form EV against the binomial distribution. Equals targetRTP. */
export function expectedValue(
  rows: PlinkoRows,
  riskLevel: RiskLevel = DEFAULT_RISK,
): number {
  const probs = binomialProbabilities(rows);
  const mults = getMultipliers(rows, riskLevel);
  return probs.reduce((s, p, k) => s + p * mults[k], 0);
}

/** Format a multiplier for UI display. Casino-style, no scientific notation. */
export function formatMultiplier(m: number): string {
  if (m >= 100) return `${Math.round(m)}x`;
  if (m >= 10) return `${m.toFixed(1)}x`;
  if (m >= 1) return `${m.toFixed(2)}x`;
  return `${m.toFixed(2)}x`;
}

/** Color tier for canvas/CSS use. */
export function multiplierColor(multiplier: number): string {
  if (multiplier >= 50) return '#ff2b2b';
  if (multiplier >= 8) return '#ff6a1a';
  if (multiplier >= 2) return '#ffa61a';
  if (multiplier >= 1) return '#ffd23f';
  if (multiplier >= 0.5) return '#5a6b84';
  return '#ff5544';
}
