#!/usr/bin/env tsx
/**
 * Reads Foundry artifacts, extracts .abi, and writes packages/abi/src/abi.ts
 * as typed const exports.
 *
 * Run with: pnpm sync:abi
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');
const outPath = resolve(repoRoot, 'packages/abi/src/abi.ts');

const contracts = [
  {
    exportName: 'procrastinotAbi',
    source: 'contracts/out/Procrastinot.sol/Procrastinot.json',
  },
  {
    exportName: 'degenVaultAbi',
    source: 'contracts/out/DegenVault.sol/DegenVault.json',
  },
] as const;

function readAbi(source: string): unknown[] {
  const artifactPath = resolve(repoRoot, source);
  if (!existsSync(artifactPath)) {
    console.error(`[sync-abi] Foundry artifact not found at ${artifactPath}`);
    console.error(`[sync-abi] Run \`cd contracts && forge build\` first.`);
    process.exit(1);
  }

  const artifact = JSON.parse(readFileSync(artifactPath, 'utf8')) as { abi: unknown };
  if (!Array.isArray(artifact.abi)) {
    console.error(`[sync-abi] artifact.abi is not an array for ${source}`);
    process.exit(1);
  }

  return artifact.abi;
}

const banner = `// Auto-generated by scripts/sync-abi.ts. Do not edit by hand.
// Sources:
${contracts.map((contract) => `// - ${contract.source}`).join('\n')}
`;
const body = contracts
  .map((contract) => {
    const abi = readAbi(contract.source);
    console.log(`[sync-abi] read ${abi.length} ABI entries from ${contract.source}`);
    return `export const ${contract.exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  })
  .join('\n');

writeFileSync(outPath, banner + body);
console.log(`[sync-abi] wrote ${contracts.length} ABI exports to ${outPath}`);
