#!/usr/bin/env tsx
/**
 * Reads contracts/out/Procrastinot.sol/Procrastinot.json (Foundry artifact),
 * extracts .abi, and writes packages/abi/src/abi.ts as a typed const.
 *
 * Run with: pnpm sync:abi
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');
const artifactPath = resolve(repoRoot, 'contracts/out/Procrastinot.sol/Procrastinot.json');
const outPath = resolve(repoRoot, 'packages/abi/src/abi.ts');

if (!existsSync(artifactPath)) {
  console.error(`[sync-abi] Foundry artifact not found at ${artifactPath}`);
  console.error(`[sync-abi] Run \`cd contracts && forge build\` first.`);
  process.exit(1);
}

const artifact = JSON.parse(readFileSync(artifactPath, 'utf8')) as { abi: unknown };
if (!Array.isArray(artifact.abi)) {
  console.error('[sync-abi] artifact.abi is not an array');
  process.exit(1);
}

const banner = `// Auto-generated by scripts/sync-abi.ts. Do not edit by hand.
// Source: contracts/out/Procrastinot.sol/Procrastinot.json
`;
const body = `export const procrastinotAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
writeFileSync(outPath, banner + body);
console.log(`[sync-abi] wrote ${artifact.abi.length} ABI entries to ${outPath}`);
